### PR TITLE
Docker automation for cstar_perf development

### PR DESCRIPTION
**Pull request by EnigmaCurry**
**This is still a WIP - about 90% done and usable, but don't merge yet**

This is cstar_docker,  a tool to automatically setup all of cstar_perf inside of containers to make it easier to play around with cstar_perf as well as to develop on cstar_perf.

Example:

Build the base image:

    cstar_docker build

Launch a 3 node (+1 client node) cluster (-m says to mount your local git checkout as the code to run inside the container):

    cstar_docker launch test_cluster 3 -m

Launch a single node for the frontend:

    cstar_docker frontend test_frontend -m

Hook up the test_cluster to the frontend, so the frontend can run jobs on test_cluster:

    cstar_docker associate test_frontend test_cluster

Login to the first node of test_cluster:

    cstar_docker ssh test_cluster 0

Start or stop clusters:

    cstar_docker stop test_cluster
    cstar_docker start test_cluster

List all clusters (started and stopped):

    cstar_docker list

List info about a single cluster (node ip addresses etc):

    cstar_docker info test_cluster

Destroy clusters:

    cstar_docker destroy test_cluster
    cstar_docker destroy test_frontend

    or:

    cstar_docker destroy all

There are 2 default users created for the frontend:

admin@admin.com/admin
user@user.com/user
 

IMPORTANT: The docker instances have the **host** memory, so you might want to limit what cassandra uses, otherwise you might get some OOM issues.  ie:
```
MAX_HEAP_SIZE=1024M
HEAP_NEWSIZE=500M
```

### CODE REVIEW

**Comment by EnigmaCurry** [comment]
Every command above is working except for the associate command, so the connection between the frontend and the client is still not automated. Also, no default password is applied to the frontend yet, so one needs to be manually inserted into the database.

**Comment by EnigmaCurry** [comment]
@aboudreault just a ping because I thought you'd be interested. No rush for a review, as this is mostly self contained code and still WIP.

**Comment by aboudreault** [comment]
Works like a charm @EnigmaCurry. Very nice work :) 

Suggestion: We could add a command that creates an admin user. ie. cstar_docker create_user admin -p admin. Useful for development

**Comment by aboudreault** [comment]
Currently, it seems that we cannot change the C* jvm memory.  The C* inside the docker instance picks the default value, which is the 1/4 of the entire *host* ram. This something leads to C* being killed by the OOM:
```
Memory cgroup out of memory: Kill process 2931
(java) score 995 or sacrifice child
[1549771.065308] Killed process 2931 (java) total-vm:6190592kB
```

A line like the following doesn't seem to work, since the memory parameters will be specified twice when launching C*:
``` 
"env": "JVM_OPTS=\"$JVM_OPTS -Xms8192M\"\nJVM_OPTS=\"$JVM_OPTS -Xmx8192M\"\nJVM_OPTS=\"$JVM_OPTS -Xmn2048M\"",
```

**Comment by EnigmaCurry** [comment]
Can't you just override MAX_HEAP_SIZE and HEAP_NEWSIZE in env?

**Comment by EnigmaCurry** [comment]
And shouldn't you be on vacation? ;)

**Comment by aboudreault** [comment]
Yes Yes, leaving soon :). I'll give it a try, but since "env" lines are simply appended to the cassandra-env.sh file, they will not be taken into account until the end of the file so the JVM_OPTS will already have its options.

**Comment by EnigmaCurry** [comment]
env is PREpended, so it should work.

**Comment by EnigmaCurry** [comment]
One thing I would change here is the things in tasks.py, some of this should be moved to tool/fab_deploy.py - basically I want to abstract the fabric tasks for deployment into this package so that it can be reused to install cstar_perf in non-docker environments. Let's keep the docker specific stuff separate from general deployment tasks.

**Comment by aboudreault** [comment]
Good point. will do.

**Comment by aboudreault** [comment]
Yep, it seems to work well setting MAX_HEAP_SIZE and HEAD_NEWSIZE. Not sure why I thought env was appended and not prepended. Thanks!

**Comment by aboudreault** [comment]
I refactored a bit tasks to only contain the docker related tasks. The other ones have been move to fab_deploy.py as requested.

**Pull request merged**
