### PR TITLE
Allow specifying the DSE node type

### PR DESCRIPTION
**Pull request by nastra**
This PR will add support to specifying the DSE node type (http://docs.datastax.com/en/datastax_enterprise/4.8/datastax_enterprise/startStop/refDseStandalone.html) when running tests against DSE.

dse-node-type

### CODE REVIEW

**Comment by nastra** [comment]
@EnigmaCurry / @aboudreault can you guys review please once you have some time?

**Comment by aboudreault** [comment]
I will try to tackle this this PM or tomorrow morning.

**Comment by aboudreault** [comment]
Sorry @nastra , I will do my best to review and test this PR today

**Comment by aboudreault** [comment]
rebased. LGTM! Thanks! sorry for the delay.

**Comment by nastra** [comment]
no worries about the delay. Thanks

**Pull request merged**
