### PR TITLE
Fix several issues using selenium from docker as well as an issue rendering revisions by of revision by revision label

### PR DESCRIPTION
**Pull request by EnigmaCurry**
Merged version of PR #119 to resolve conflicts and to bring into this repository.

### CODE REVIEW

**Comment by EnigmaCurry** [comment]
Closing this in favor of #134 - I have fixed some merge conflicts and should be up to date with trunk.

@aboudreault - I merged this with some flame graph stuff, can you smoke test this?

**Comment by aboudreault** [comment]
yes, will give it a try locally

**Comment by aboudreault** [comment]
I will test that on monday! sorry for the delay.

**Comment by aboudreault** [comment]
@EnigmaCurry I've rebased, fix conflicts and tested. LGTM. Question: looks like I lost your commit in the rebase ... no idea why since it was a normal rebase. Can you double check that your changes are in this PR using your local branch?

**Pull request merged**
