### PR TITLE
Provide example of how to use cstar_perf_bootstrap with a DSE version. Also specify -v flag when using cstar_perf_bootstrap

### PR DESCRIPTION
**Pull request by nastra**
Here's how the diff looks in the documentation:
diff

### CODE REVIEW

**Comment by aboudreault** [comment]
Thanks!

**Comment by nastra** [comment]
@aboudreault wow you're fast with reviewing :)

**Comment by aboudreault** [comment]
heh ;)

**Comment by EnigmaCurry** [comment]
@nastra you edited the compiled html, you need to edit the rst here : https://github.com/datastax/cstar_perf/blob/gh-pages/source/setup_cstar_perf_tool.rst

**Comment by aboudreault** [comment]
I did the exact same thing last time I edited docs, so haven't noticed that! Thanks Ryan!

**Comment by nastra** [comment]
Ok thanks for the info, I will adjust that.

**Comment by nastra** [comment]
See https://github.com/datastax/cstar_perf/pull/128 for the adjustment

**Pull request merged**
