### PR TITLE
(WIP) Initial support of DSE for cstar_perf_tool

### PR DESCRIPTION
**Pull request by aboudreault**
(WIP) Do not merge.

Add the DSE support to cstar_perf_tool.  Currently supported:

* Download the DSE binaries from the url config (dse-REVISION-bin.tar.gz)
* Cache DSE binaries on the *cstar_perf_tool server* (download only once, since DSE is ~500mb) 
* Setup DSE binaries in ~/fab
* Start Cassandra using bin/dse utility (DseDamon)
* Ensure things are started and running
* Product selection in the frontend (Cassandra or DSE)
* cstar_perf_stress should then work as normal

Misc Additions
* fab_common.py is now the main fabric tasks file. Based on the choosed product, it calls the proper functions from fab_cassandra.py or fab_dse.py
* JNA can now be downloaded from the web: (https://github.com/apache/cassandra/raw/trunk/lib/jna-4.0.0.jar)

### Cluster Configuration

This is what you need in cluster configuration:

```json
    "dse_url": "http://my-dse-repo/tar",
    "dse_username": "XXXX",
    "dse_password": "YYYY", 
    "dse_cache_dir": "/home/vagrant/dse_cache"
```

### Possible Improvements
* Set DSE product optional, currently an error will be raised during benchmark setup
* Check md5sum of the dse file before skipping the download
* Refactor the fab_common, fab_cassandra, fab_dse file. ie. it would be cleaner to have a kind of Configurator class and having 2 subclasses: CassandraConfigurator and DseConfigurator.

#### cstar_perf_tool

```json
{
 "product": "dse",
 "ant_tarball": "http://www.apache.org/dist/ant/binaries/apache-ant-1.8.4-bin.tar.bz2",
 "block_devices":["/dev/sda"],
 "blockdev_readahead":"256",
 "cluster_name":"cstar_perf 7EEN4LQJFE",
 "commitlog_directory":"/home/vagrant/fab/node_data/commitlog",
 "data_file_directories":["/home/vagrant/fab/node_data/data"],
 "env":"",
 "flush_directory":"/home/vagrant/fab/node_data/flush",
 "git_repo":"git://github.com/apache/cassandra.git",
 "java_home":"~/fab/java",
 "log_dir":"~/fab/cassandra/logs",
 "num_tokens":256,
 "override_version":null,
 "partitioner":"murmur3",
 "revision":"4.6.2",
 "saved_caches_directory":"/home/vagrant/fab/node_data/saved_caches",
 "use_jna":true,
 "use_vnodes":true,
 "user":"vagrant"
}
```

#### cstar_perf_stress

```json
{
 "revisions":[
    {"product": "dse", "revision":"4.6.2"},
    {"product": "dse", "revision":"4.6.2", "memtable_allocation_type":"offheap_objects"}
 ],
 "title":"Test DSE offheap memtables",
 "log":"stats.dse-4.6.2.offheap_memtables.json",
 "operations": [
    {"type":"stress","command":"write n=65 -rate threads=40 -mode cql3 native"},
    {"type":"stress","command":"read n=65 -rate threads=40 -mode cql3 native"},
    {"type":"stress","command":"read n=65 -rate threads=40 -mode cql3 native"}]
}
```

### CODE REVIEW

**Comment by aboudreault** [comment]
@EnigmaCurry here is the initial commit for the DSE support.

**Comment by aboudreault** [comment]
Just pushed the changes to be able to select the product in the frontend. Work well but need some more tests.

**Comment by aboudreault** [comment]
@EnigmaCurry Can you give a try to this branch sometime next week? I got many successful tests with it locally. One thing I've noticed is that a few tests fail because the compaction was never ending on the server, so perf.tool was asking the status forever... I will need to retest and investigate about this one.

**Comment by EnigmaCurry** [comment]
Closing this in favor of #48 which is the same thing just that I brought the branch internal to the cstar_perf repository so we can both work on it. I'm granting you commit privileges too @aboudreault.

**Pull request closed without merging**
