### PR TITLE
Perf regression vers cleanup/update

### PR DESCRIPTION
**Pull request by knifewine**
make rolling version tests cover new versions, and remove versions not needed, along with some code cleanup to make things more maintainable.

### CODE REVIEW

**Comment by mambocab** [comment]
Passes visual inspection. Have you been able to run this anywhere?

**Comment by knifewine** [comment]
I can run this locally with the dummy scheduler, and see the json output, but that's it.

**Comment by mambocab** [comment]
Cool - if that looks like what you expect, then +1.

**Comment by mambocab** [comment]
You should have write permissions now -- feel free to merge when ready.

**Comment by knifewine** [comment]
ok, I compared pre-patch json format to post-patch json format, and double checked that sha searching found the same revisions for trunk. looks good, merging.

**Pull request merged**
