### PR TITLE
Add support for dse.yaml settings

### PR DESCRIPTION
**Pull request by nastra**
This PR will add support for configuring `dse.yaml` settings. The `dse.yaml` div container in the UI will also only be shown if `dse` is selected from the product dropdown.

### CODE REVIEW

**Comment by aboudreault** [comment]
The code looks good to me. I will give this a try locally.

**Comment by nastra** [comment]
@aboudreault in case you wanna run those things in a docker container with DSE enabled, you can take a look at https://gist.github.com/nastra/13e8480bbb0500bc835c

**Comment by aboudreault** [comment]
@nastra when you got a minute, can you add me as collaborator of you cstar_perf repo? I have to push 3 minor fixes and we'll be good to merge. I've also rebased on latest master.

**Comment by EnigmaCurry** [comment]
If it makes it easier, for future PRs you can create a branch directly on
this repo @nastra, you have access. That way we can push fixes onto the
same PR.

**Comment by nastra** [comment]
@aboudreault I don't have an own cstar_perf repo, I'm pushing directly to the datastax cstar_perf repo and the changes are on the branch `ET-dseyaml-support`, so you should have access to that branch

**Comment by aboudreault** [comment]
sorry, my bad. I added your github remote by habits  and was sure the branch was there then.

**Comment by aboudreault** [comment]
Just pushed my minor fixes. The first one is to show dse yaml when cloning a job. Thanks for you work!!

**Comment by nastra** [comment]
@aboudreault thanks for the fixes

**Pull request merged**
