### PR TITLE
Add dse / dsetool operations

### PR DESCRIPTION
**Pull request by nastra**
This PR will add support for running the operations `dse` and `dsetool`. Those two operations will only be visible if **dse** is selected as a product.

For the `dse` command the user can select **one** node as the execution node. The `dsetool` command on the other hand can run on **N** nodes where **1 <= N <= cluster_nodes**.

dse-operations

### CODE REVIEW

**Comment by mambocab** [comment]
Code looks reasonable, but I need to figure out an environment to run this on. @mshuler Did you figure out if there was a staging environment, or will I have to figure out the `cstar_docker` stuff to run this?

**Comment by nastra** [comment]
@mambocab you can easily run & test this with **cstar_docker** as described in http://datastax.github.io/cstar_perf/setup_dev_environment.html (with the DSE-related infos I sent you)

**Comment by jsoedomo** [comment]
@nastra thanks... this would definitely help with the Advance Replication benchmarking!!!
+1 overall :)

**Comment by mambocab** [comment]
Frontend work is good. I'm still working on a testing env that works properly, so I haven't run it against an actual cluster. But, doesn't look like it'll knock things over, so I'm +1. Kicking it to @mshuler to merge and deploy.

**Comment by mshuler** [comment]
Merged - I'll do the deployment on cstar.datastax.com Monday morning. Thanks!

**Comment by mshuler** [comment]
cstar.datastax.com updated and restarted!

**Pull request merged**
