### PR TITLE
Add javascript templating and mustache.js dependency

### PR DESCRIPTION
**Pull request by TheRealFalcon**
The string templates in **schedule.js** are hard to modify and error prone. This PR is for adding a **mustache.js** dependency and moving the templates into their own independent html files.

### CODE REVIEW

**Comment by mambocab** [comment]
We've been having some discussion about how to pull this code apart. This looks like one reasonable tack, but I'm focusing on dtest failures at the moment and won't have time to review for a bit -- sorry for the delay, but I likely won't get to it this week.

**Comment by mambocab** [comment]
To be clear: I don't think we should merge this until there's some consensus -- I guess between me and @nastra? -- that `mustache.js` is a good library to use for this, or at least won't be difficult to migrate off of if we decide not to use it long-term.

**Comment by mambocab** [comment]
@nastra: @TheRealFalcon has talked me through this PR, and his changes seem like a reasonable step making the frontend more maintainable. Could you please pull down his changes and smoke test them, since you've got a working local environment? Thanks.

**Comment by nastra** [comment]
sorry yes, didn't have time yet to do it, but will do it today/tomorrow. @TheRealFalcon can you please resolve the merge conflicts so that I can get started?

**Comment by TheRealFalcon** [comment]
@nastra rebased and pushed.

**Comment by nastra** [comment]
+1

**Comment by TheRealFalcon** [comment]
I found a couple clone issues on this branch when trying to merge it with the solr stress one.

**Pull request merged**
