### PR TITLE
added option for static vnode tokens

### PR DESCRIPTION
**Pull request by nutbunnies**
Issue #91 

Added option `static_vnode_token_group` to set tokens in vnode configuration to a static set of groups.  3 groups are available for murmur3 and random partitioners: [`group1`, `group2`, `group3`]  Additional `symmetric` group is available on clusters with node counts of 1,2,3,4,6, and 12.  Not sure if symmetric adds value as it will never happen in real world but thought it would be interesting.

Currently limited to node counts <= 12 and only for 256 tokens per node.  

Example:
```
{
  "revisions": [
    {"revision": "apache/cassandra-2.2", "cluster_name": "upgrading_cluster", "options": {"use_vnodes": true, "static_vnode_token_group": "group1"}}
  ],
  "title": "static vnode test",
  "log":"stats.version_overrides5.json",
  "operations": [
    {"type": "stress", "command": "write n=50K -rate threads=5", "wait_for_compaction": true }
  ]
}
```

Should the token blocks be formatted to the pep8 max line length?

### CODE REVIEW

**Comment by aboudreault** [comment]
LGTM. I haven't played much with tokens and vnodes yet. Would be good to have @EnigmaCurry or @ptnapoleon take a quick look at this. Thanks

**Comment by ptnapoleon** [comment]
Is there any meaning behind the chosen groups? Or did you just randomly generate them.

**Comment by EnigmaCurry** [comment]
@belliottsmith can you take a look at static_vnode_tokens.py in this PR? Is this what you're looking for?

**Comment by nutbunnies** [comment]
@ptnapoleon - Outside of the symmetrical one, no meaning.  I just scripted bootstrapping a 3.0 C* cluster with the different partitioners and extracted the tokens.

**Comment by belliottsmith** [comment]
From a UI perspective, it would be nice to have a shared option across all runs for setting this (that could perhaps be overridden for special occasions), and for the "use vnodes" boolean to just be another option for a token group.

Otherwise it looks good, but I would ensure we have only one group per kind of allocation: non-vnode, static, random, and the results of one run of branimir's new allocation strategy, and named appropriately.

**Comment by nutbunnies** [comment]
- I've added a static token set from the new token allocation (CASSANDRA-7032).  
- removed extra groups and symmetric token groups
- UI now has a pull down for token allocation with the options:
```
non-vnodes
vnodes (random)
vnodes (static-random)
vnodes (static-algorithmic)
```
- in the json the `use_vnodes` boolean contract is still present and will use the random vnode allocation (same as before) behavior.  Existing json test files should run as expected with no change.
- new json option `token_allocation` for setting with the options:
```
random
static-random
static-algorithmic
```

**Comment by nutbunnies** [comment]
rebased on master and fixed conflicts

@EnigmaCurry and @aboudreault can you give it one more look before merging?

**Comment by aboudreault** [comment]
LGTM

**Pull request merged**
